//! Renders the caller workflow that `deepcode github install` writes.
//!
//! The generated file is deliberately tiny: it turns the bot on and passes
//! secrets, while the pipeline itself stays in this project's reusable
//! workflow. That is what lets a fix here reach every installation through a
//! one-line version bump instead of a re-copied template.

use std::fmt::Write as _;

/// The published pipeline. Consumers pin it by tag, so the ref is what decides
/// which version of the bot a repository runs.
pub(crate) const REUSABLE_WORKFLOW: &str = "liwenka1/deep-code/.github/workflows/deepcode-bot.yml";

pub(crate) const API_KEY_SECRET: &str = "DEEPSEEK_API_KEY";
pub(crate) const APP_ID_SECRET: &str = "DEEPCODE_APP_ID";
pub(crate) const APP_KEY_SECRET: &str = "DEEPCODE_APP_PRIVATE_KEY";

/// Default location of the generated file inside the target repository.
pub(crate) const DEFAULT_WORKFLOW_PATH: &str = ".github/workflows/deepcode.yml";

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct WorkflowSpec {
    /// Git ref of the reusable workflow, e.g. `v0.5.0`. Pinned, never a branch:
    /// a moving ref would silently change what runs in someone's CI.
    pub workflow_ref: String,
    /// Wire up the optional GitHub App secrets.
    pub with_app: bool,
    /// `zh` | `en` — language of the bot's own canned text.
    pub lang: String,
    /// Permission tier the agent runs under. `accept_edits` is the useful
    /// default; `default` would auto-deny every write and the bot could answer
    /// but never change a file.
    pub permission_mode: String,
    /// Version of the CLI that generated the file, recorded in the header.
    pub generator_version: String,
}

pub(crate) fn render(spec: &WorkflowSpec) -> String {
    let mut out = String::new();
    let _ = write!(
        out,
        "name: deep-code\n\
         \n\
         # Generated by `deepcode github install` (deep-code {version}).\n\
         # This file only turns the bot on — the pipeline lives in the reusable\n\
         # workflow referenced below, so updating means bumping its ref.\n\
         # Inputs and the security model are documented in that workflow's header:\n\
         # https://github.com/{repo}\n\
         #\n\
         # By default only the repository OWNER can trigger it. Widening that hands\n\
         # anyone who can comment the ability to run shell in this CI, next to these\n\
         # secrets — read the security notes before changing `allowed-associations`.\n\
         \n\
         on:\n  \
           issue_comment:\n    \
             types: [created]\n\
         \n\
         jobs:\n  \
           deepcode:\n    \
             # What the pipeline needs to push a branch, open a PR, and reply.\n    \
             permissions:\n      \
               contents: write\n      \
               pull-requests: write\n      \
               issues: write\n    \
             uses: {workflow}@{git_ref}\n    \
             with:\n      \
               lang: {lang}\n      \
               permission-mode: {mode}\n    \
             secrets:\n      \
               deepseek-api-key: ${{{{ secrets.{api_key} }}}}\n",
        version = spec.generator_version,
        repo = REUSABLE_WORKFLOW.split("/.github/").next().unwrap_or(""),
        workflow = REUSABLE_WORKFLOW,
        git_ref = spec.workflow_ref,
        lang = spec.lang,
        mode = spec.permission_mode,
        api_key = API_KEY_SECRET,
    );

    if spec.with_app {
        let _ = write!(
            out,
            "      # Acting as your own GitHub App: commits count toward contributors,\n\
             \x20     # comments carry a [bot] badge, and bot pushes trigger your other\n\
             \x20     # workflows (a GITHUB_TOKEN push does not).\n\
             \x20     app-id: ${{{{ secrets.{app_id} }}}}\n\
             \x20     app-private-key: ${{{{ secrets.{app_key} }}}}\n",
            app_id = APP_ID_SECRET,
            app_key = APP_KEY_SECRET,
        );
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec(with_app: bool) -> WorkflowSpec {
        WorkflowSpec {
            workflow_ref: "v0.5.0".to_string(),
            with_app,
            lang: "zh".to_string(),
            permission_mode: "accept_edits".to_string(),
            generator_version: "0.5.0".to_string(),
        }
    }

    #[test]
    fn renders_a_pinned_reference_and_the_required_secret() {
        let yaml = render(&spec(false));
        assert!(
            yaml.contains("uses: liwenka1/deep-code/.github/workflows/deepcode-bot.yml@v0.5.0")
        );
        // The `${{ }}` braces must survive format!'s escaping.
        assert!(yaml.contains("deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY }}"));
        assert!(!yaml.contains("app-id"), "no App wiring unless asked");
    }

    #[test]
    fn app_variant_adds_both_secrets_and_nothing_else_changes() {
        let plain = render(&spec(false));
        let with_app = render(&spec(true));
        assert!(with_app.contains("app-id: ${{ secrets.DEEPCODE_APP_ID }}"));
        assert!(with_app.contains("app-private-key: ${{ secrets.DEEPCODE_APP_PRIVATE_KEY }}"));
        // The App variant must be a pure superset — same trigger, same job.
        assert!(with_app.starts_with(plain.trim_end_matches('\n')));
    }

    #[test]
    fn yaml_indentation_is_well_formed() {
        let yaml = render(&spec(true));
        // Spot-check the nesting levels a broken format! string would mangle.
        for expected in [
            "on:\n  issue_comment:\n    types: [created]",
            "jobs:\n  deepcode:",
            "    permissions:\n      contents: write",
            "    secrets:\n      deepseek-api-key:",
        ] {
            assert!(
                yaml.contains(expected),
                "missing block:\n{expected}\n---\n{yaml}"
            );
        }
        assert!(
            yaml.lines().all(|line| !line.contains('\t')),
            "tabs are invalid YAML indentation"
        );
    }

    #[test]
    fn header_records_the_generator_and_warns_about_the_trigger_gate() {
        let yaml = render(&spec(false));
        assert!(yaml.contains("deepcode github install"));
        assert!(yaml.contains("deep-code 0.5.0"));
        assert!(
            yaml.contains("allowed-associations"),
            "the security note must travel with the generated file"
        );
    }
}
